Repository openkm/document-management-system, pull requests merged in 2022-05, with the labels that each got.

#327 Remove DES from SecureStore
  src/main/java/com/openkm/util/SecureStore.java
Labels: clean code

#326 Wrong major minor increment version in the UI
  src/main/java/com/openkm/frontend/client/bean/GWTWorkspace.java
  src/main/java/com/openkm/servlet/frontend/WorkspaceServlet.java
Labels: bug

#312 Extend DashboardService API
  src/main/java/com/openkm/rest/endpoint/DashboardService.java
  src/main/java/com/openkm/rest/util/DashboardDocumentResultList.java
  src/main/java/com/openkm/rest/util/DashboardFolderResultList.java
  src/main/java/com/openkm/rest/util/DashboardMailResultList.java
  src/main/webapp/WEB-INF/rest.xml
Labels: enhancement

#316 Bug getting general dashboard files
  make-all.sh
  src/main/java/com/openkm/api/OKMDashboard.java
  src/main/java/com/openkm/dao/NodeDocumentDAO.java
  src/main/java/com/openkm/dao/NodeFolderDAO.java
  src/main/java/com/openkm/frontend/client/service/OKMDashboardService.java
  src/main/java/com/openkm/frontend/client/service/OKMDashboardServiceAsync.java
  src/main/java/com/openkm/frontend/client/widget/dashboard/GeneralDashboard.java
  src/main/java/com/openkm/module/DashboardModule.java
  src/main/java/com/openkm/module/db/DbDashboardModule.java
  src/main/java/com/openkm/servlet/frontend/DashboardServlet.java
  src/main/java/com/openkm/util/UserActivity.java
  src/main/resources/i18n/en-GB.sql
  src/main/resources/i18n/es-ES.sql
Labels: bug

#324 Document Service end point does not consider the "increment" field du…
  src/main/java/com/openkm/rest/endpoint/DocumentService.java
Labels: bug
